import {useEffect,useRef,useState} from 'react';
import {backupDirectory,backupTargets,removeBackupTarget,chooseBackupDirectory,saveRecovery,snapshots} from '@/lib/recovery';
import {importLesson} from '@/lib/lesson-bundle';
import {download} from './ExportPanel';
export function RecoveryPanel({lessonId,flush}:{lessonId:string;flush:()=>Promise<void>}) {
 const [open,setOpen]=useState(false),[status,setStatus]=useState('Folder backup not enabled'),[busy,setBusy]=useState(false),[copies,setCopies]=useState<Awaited<ReturnType<typeof snapshots>>>([]);
 const [provider,setProvider]=useState('Local folder'),[destinations,setDestinations]=useState<Awaited<ReturnType<typeof backupTargets>>>([]),[targetStatus,setTargetStatus]=useState<{label:string;ok:boolean;message:string}[]>([]);
 const latestFlush=useRef(flush);latestFlush.current=flush;const running=useRef(false);
 async function backup(){if(running.current)return;running.current=true;setBusy(true);try{await latestFlush.current();const result=await saveRecovery(lessonId);setStatus(`${result.external?'Folder + local backup':'Local recovery only'} · ${new Date(result.savedAt).toLocaleTimeString()}`);setCopies(await snapshots(lessonId));setTargetStatus(result.targets);setDestinations(await backupTargets());}catch(error){setStatus('Backup failed: '+(error instanceof Error?error.message:'Check available storage'));}finally{running.current=false;setBusy(false);}}
 useEffect(()=>{const timer=window.setInterval(()=>void backup(),30000);void snapshots(lessonId).then(setCopies);void backupTargets().then(setDestinations);return()=>clearInterval(timer);},[lessonId]);
 return <div className="recovery-control"><button aria-expanded={open} onClick={()=>setOpen(!open)}>Backups</button>{open&&<section className="recovery-panel" aria-label="Lesson backups"><h2>Keep your lesson safe</h2><p role="status">{status}</p><p>Autosave stores completed edits locally. Every 30 seconds while this board is open, three recovery versions rotate. Choose a folder to keep three additional files outside browser storage.</p><p>Local recovery is lost if site data is cleared. Folder files survive clearing site data or uninstalling the app if you keep that folder. The latest unsaved stroke may be lost during a power failure.</p>
 <label className="block mb-3">Backup destination <select aria-label="Backup destination" value={provider} onChange={e=>setProvider(e.target.value)} className="p-2 border rounded"><option>Local folder</option><option>Google Drive folder</option><option>OneDrive folder</option><option>Dropbox folder</option><option>Nextcloud folder</option><option>Other synced folder</option></select></label><p>Select a folder inside the provider's installed desktop sync app. Kopy saves files there; the provider app uploads them. This does not sign you into a cloud account or merge simultaneous edits.</p>
 <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void (async()=>{try{const existing=await backupDirectory(provider);if(existing&&await existing.requestPermission({mode:'readwrite'})==='granted')await backup();else{await chooseBackupDirectory(provider);await backup();}}catch(e){setStatus(e instanceof Error?e.message:'Folder access cancelled');}})()}>Enable folder backup</button><button disabled={busy} onClick={()=>void backup()}>Back up now</button><button disabled={busy} onClick={()=>void (async()=>{await backup();const list=await snapshots(lessonId);if(list[0])download(URL.createObjectURL(list[0].blob),'lesson-backup.kopy');})()}>Download backup</button></div>
 {destinations.map(target=><div className="recovery-row" key={target.label}><span>{target.label} · {target.directory.name}</span><button disabled={busy} onClick={()=>void removeBackupTarget(target.label).then(async()=>setDestinations(await backupTargets()))}>Disconnect</button></div>)}{targetStatus.map(target=><p key={target.label}>{target.label}: {target.ok?'Saved locally in folder':'Needs attention'} · {target.message}</p>)}
 <button disabled={busy} onClick={()=>void snapshots().then(setCopies)}>Recovery from all lessons</button>
 {copies.map(copy=><div key={copy.id} className="recovery-row"><span>{new Date(copy.savedAt).toLocaleString()}</span><button disabled={busy} onClick={()=>void (async()=>{setBusy(true);try{await latestFlush.current();const id=await importLesson(copy.blob);window.location.hash=`/board/${id}`;setOpen(false);}catch(e){setStatus(e instanceof Error?e.message:'Restore failed');}finally{setBusy(false);}})()}>Restore as copy</button></div>)}
 <p>After reinstalling, import any saved .kopy file from the Import menu. Re-enable folder permission after reopening the browser.</p></section>}</div>;
}
