import {test,expect,type Page} from '@playwright/test';
import {selectOption} from '../helpers/custom-select';
async function board(page:Page,dark=false){
 await page.goto('/#/app');await page.waitForFunction(()=>document.body.textContent?.includes('Kopy'));
 const data=await page.evaluate(async(dark)=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);const {BUILTIN_THEMES}=await import('/src/lib/theme-pack.ts' as string);const c=document.createElement('canvas');c.width=c.height=8;c.getContext('2d')!.fillRect(0,0,8,8);const image=c.toDataURL();await localRequest('/api/profile',{method:'PUT',body:JSON.stringify({onboarded:1,boardBg:'#234567',boardPattern:'grid',boardImage:image,theme:dark?{...BUILTIN_THEMES[2],colors:{...BUILTIN_THEMES[2].colors,panel:'#111111',surface:'#1d1d1d'}}:BUILTIN_THEMES[0],ui:{flipMenuOnSwap:true,toolPopupOnFirstClick:true}})});const {notebook}=await(await localRequest('/api/notebooks',{method:'POST',body:JSON.stringify({title:'Interface polish'})})).json();const {pages}=await(await localRequest(`/api/notebooks/${notebook.id}`)).json();return{id:notebook.id,pageId:pages[0].id,image};},dark);
 await page.goto(`/#/board/${data.id}`);await page.reload();await expect(page.getByRole('button',{name:'Pen',exact:true})).toBeVisible();return data;
}
test('next blank page after a document restores the saved background image and pattern',async({page})=>{
 const data=await board(page);await page.evaluate(async(id)=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);await localRequest(`/api/pages/${id}`,{method:'PUT',body:JSON.stringify({background:'#ffffff',pattern:'none',backgroundImage:'',importFrame:{x:0,y:0,width:1280,height:720}})});},data.pageId);await page.reload();await page.getByRole('button',{name:'Add page',exact:true}).click();await expect(page.getByRole('button',{name:'Open slides',exact:true})).toBeVisible();
 const last=await page.evaluate(async(id)=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);return(await(await localRequest(`/api/notebooks/${id}`)).json()).pages.at(-1);},data.id);expect(last.background).toBe('#234567');expect(last.pattern).toBe('grid');expect(last.backgroundImage).toBe(data.image);
});
test('dark controls, saved visibility and reversed dock order remain consistent',async({page})=>{
 await board(page,true);expect(await page.locator('.kn-slides-panel').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(17, 17, 17)');expect(await page.locator('.kn-main-tools').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(17, 17, 17)');await expect(page.getByText('Slides',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Teaching controls',exact:true}).click();await page.getByLabel('Show Fullscreen',{exact:true}).uncheck();await page.getByRole('button',{name:'Done',exact:true}).click();await expect(page.getByRole('button',{name:'Enter fullscreen',exact:true})).toBeHidden();
 await page.getByRole('button',{name:'Swap menu and slide controls',exact:true}).click();expect(await page.locator('.kn-dock').evaluate(el=>getComputedStyle(el).flexDirection)).toBe('row-reverse');await page.reload();await expect(page.getByRole('button',{name:'Enter fullscreen',exact:true})).toBeHidden();
});
test('custom dropdown works and tool popups stay visible beside both side docks',async({page})=>{
 await board(page);await page.getByRole('button',{name:'Pen',exact:true}).click();await page.getByRole('button',{name:'Writing and touch settings',exact:true}).click();await selectOption(page.getByLabel('Touch behavior'),'reject');await expect(page.getByLabel('Touch behavior')).toHaveText(/Pen only/);await page.getByRole('button',{name:'Close writing and touch',exact:true}).click();
 for(const side of ['left','right']){await page.getByRole('button',{name:'Teaching controls',exact:true}).click();await page.getByRole('button',{name:`Dock ${side}`,exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();if(!await page.getByLabel('Pen options',{exact:true}).isVisible())await page.getByRole('button',{name:'Pen',exact:true}).click();await expect.poll(async()=>{const popup=await page.getByLabel('Pen options',{exact:true}).boundingBox(),toolbar=await page.locator('.board-toolbar').boundingBox();return !!popup&&!!toolbar&&popup.x>=7&&popup.x+popup.width<=1273&&(side==='left'?popup.x>=toolbar.x+toolbar.width-1:popup.x+popup.width<=toolbar.x+1);}).toBe(true);}
});

test('size feedback appears only on size changes inside pen settings',async({page})=>{
 await board(page);await page.getByRole('button',{name:'Close slides',exact:true}).click();await page.getByRole('button',{name:'Pen',exact:true}).click();await expect(page.locator('.kn-size-preview-inline')).toHaveCount(0);
 await page.getByRole('slider',{name:'Pen size',exact:true}).focus();await page.keyboard.press('ArrowRight');const preview=page.locator('.kn-size-preview-inline');await expect(preview).toBeVisible();await expect(page.getByLabel('Pen options',{exact:true}).locator('.kn-size-preview-inline')).toBeVisible();await expect(preview).toBeHidden({timeout:5000});
 await page.getByRole('button',{name:'Pen',exact:true}).click();await page.getByRole('button',{name:'Pen',exact:true}).click();await expect(preview).toHaveCount(0);
});

test('clock is bold and textured brushes cover the stroke and remember individual sizes',async({page})=>{
 await board(page);const clock=await page.locator('.board-meta>summary').evaluate(el=>({size:parseFloat(getComputedStyle(el).fontSize),weight:Number(getComputedStyle(el).fontWeight)}));expect(clock.size).toBeGreaterThanOrEqual(26);expect(clock.weight).toBeGreaterThanOrEqual(700);
 await page.getByRole('button',{name:'Pen',exact:true}).click();await page.getByRole('button',{name:'Paint',exact:true}).click();await expect(page.getByRole('slider',{name:'Pen size',exact:true})).toHaveValue('16');await page.getByRole('slider',{name:'Pen size',exact:true}).focus();await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'crayon',exact:true}).click();await expect(page.getByRole('slider',{name:'Pen size',exact:true})).toHaveValue('12');await page.getByRole('button',{name:'Paint',exact:true}).click();await expect(page.getByRole('slider',{name:'Pen size',exact:true})).toHaveValue('17');
 const pigment=await page.evaluate(async()=>{const {drawStroke}=await import('/src/lib/render.ts' as string);return ['paint','crayon','pencil'].map(brush=>{const canvas=document.createElement('canvas');canvas.width=100;canvas.height=40;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,100,40);drawStroke(ctx,{id:brush,kind:'stroke',tool:'pen',brush,color:'#000000',width:20,points:[{x:10,y:20},{x:90,y:20}]});const data=ctx.getImageData(25,16,40,8).data;const shades=new Set<number>();let sum=0;for(let i=0;i<data.length;i+=4){shades.add(data[i]);sum+=data[i];}return {brush,shades:shades.size,mean:sum/(data.length/4)};});});
 expect(pigment.every(p=>p.shades>8)).toBe(true);expect(pigment[0].mean).toBeLessThan(pigment[1].mean);expect(pigment[1].mean).toBeLessThan(200);
});
