import {test,expect,type Page} from '@playwright/test';
import {jsPDF} from 'jspdf';
async function seed(page:Page){await page.goto('/#/app');return page.evaluate(async()=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);await localRequest('/api/profile',{method:'PUT',body:JSON.stringify({onboarded:1,boardBg:'#d4e6c5',boardPattern:'grid'})});const {notebook}=await(await localRequest('/api/notebooks',{method:'POST',body:JSON.stringify({title:'PDF recovery lesson'})})).json();const {pages}=await(await localRequest(`/api/notebooks/${notebook.id}`)).json();return {id:notebook.id,pageId:pages[0].id};});}
test('PDF rendering is shared, bounded, transparent, retryable and warms the next page',async({page})=>{
 const lesson=await seed(page);const doc=new jsPDF({unit:'pt',format:[200,300]});doc.text('First page',15,30);for(let i=2;i<=4;i++){doc.addPage();doc.text('Page '+i,15,30);}const bytes=Array.from(new Uint8Array(doc.output('arraybuffer')));
 const result=await page.evaluate(async({lesson,bytes})=>{const {importPdfPages}=await import('/src/lib/pdf-pages.ts' as string),{localRequest,database}=await import('/src/lib/local-store.ts' as string),media=await import('/src/lib/media.ts' as string);await importPdfPages(lesson.id,new File([new Uint8Array(bytes)],'test.pdf',{type:'application/pdf'}),true);const data=await(await localRequest(`/api/notebooks/${lesson.id}`)).json(),assetId=data.pages[0].media[0].assetId;
 const [a,b]=await Promise.all([media.renderPdfPage(assetId,1,1600),media.renderPdfPage(assetId,1,1600)]);const alpha=a.getContext('2d')!.getImageData(2,2,1,1).data[3];const large=await media.renderPdfPage(assetId,2,8000);
 const db=await database();await db.put('assets',{id:'retry-pdf',notebookId:lesson.id,name:'retry.pdf',mimeType:'application/pdf',blob:new Blob(['broken'])});let rejected=false;try{await media.renderPdfPage('retry-pdf',1,320);}catch{rejected=true;}await db.put('assets',{id:'retry-pdf',notebookId:lesson.id,name:'retry.pdf',mimeType:'application/pdf',blob:new Blob([new Uint8Array(bytes)])});db.close();const recovered=await media.renderPdfPage('retry-pdf',1,320);
 return {same:a===b,alpha,pixels:large.width*large.height,rejected,recovered:recovered.width,background:data.pages[0].background,pattern:data.pages[0].pattern,assetId};},{lesson,bytes});
 expect(result.same).toBe(true);expect(result.alpha).toBe(0);expect(result.pixels).toBeLessThan(3_010_000);expect(result.rejected).toBe(true);expect(result.recovered).toBe(320);expect(result.background).toBe('#d4e6c5');expect(result.pattern).toBe('grid');
 await page.goto(`/#/board/${lesson.id}`);await page.reload();await expect(page.getByRole('button',{name:'Pen',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(async(id)=>{const {peekPdfPage}=await import('/src/lib/media.ts' as string);return !!peekPdfPage(id,2);},result.assetId),{timeout:15000}).toBe(true);
});
test('reopening restores the last slide and camera without moving or dropping shapes',async({page})=>{
 const lesson=await seed(page);const second=await page.evaluate(async(lesson)=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);const {page}=await(await localRequest(`/api/notebooks/${lesson.id}/pages`,{method:'POST',body:'{}'})).json();await localRequest(`/api/pages/${page.id}`,{method:'PUT',body:JSON.stringify({objects:[{id:'shape',kind:'shape',shape:'rect',x:5000,y:4000,w:100,h:80,color:'#ff0000',filled:true,width:3,rotation:.2}]})});localStorage.setItem('kopy-last-page:'+lesson.id,page.id);localStorage.setItem('kopy-view:'+page.id,JSON.stringify({tx:-4900,ty:-3900,scale:1}));return page.id;},lesson);
 await page.goto(`/#/board/${lesson.id}`);await page.reload();await expect(page.getByRole('button',{name:'Open slides',exact:true})).toHaveText('2 / 2');await expect(page.getByRole('button',{name:'Teaching controls',exact:true})).toHaveText('');
 await expect.poll(()=>page.evaluate(async(id)=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);return(await(await localRequest(`/api/pages/${id}`)).json()).page.objects[0];},second)).toMatchObject({x:5000,y:4000,w:100,h:80,rotation:.2});await page.reload();await expect(page.getByRole('button',{name:'Open slides',exact:true})).toHaveText('2 / 2');expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('kopy-view:'+id)!),second)).toEqual({tx:-4900,ty:-3900,scale:1});
});
test('interrupted drawing is offered and restored only when the teacher chooses',async({page})=>{
 const lesson=await seed(page);await page.evaluate(async(lesson)=>{const {checkpoint,recordSession}=await import('/src/lib/work-journal.ts' as string);await recordSession({lessonId:lesson.id,pageId:lesson.pageId,title:'Interrupted lesson',active:true,updatedAt:Date.now()});await checkpoint({lessonId:lesson.id,pageId:lesson.pageId,revision:'crash',savedAt:Date.now(),partial:true,edit:{background:'#d4e6c5',pattern:'grid',objects:[{id:'unfinished',kind:'shape',shape:'rect',x:100,y:100,w:120,h:100,color:'#ff0000',filled:true,width:3,rotation:0}],media:[]}});},lesson);
 await page.goto('/#/library');await page.reload();await page.getByRole('button',{name:'Open last lesson',exact:true}).click();await expect(page.getByRole('button',{name:'Restore unfinished work',exact:true})).toBeVisible();const before=await page.evaluate(async(id)=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);return(await(await localRequest(`/api/pages/${id}`)).json()).page.objects.length;},lesson.pageId);expect(before).toBe(0);await page.getByRole('button',{name:'Restore unfinished work',exact:true}).click();await expect(page.getByRole('button',{name:'Restore unfinished work',exact:true})).toBeHidden();await expect.poll(()=>page.evaluate(async(id)=>{const {localRequest}=await import('/src/lib/local-store.ts' as string);return(await(await localRequest(`/api/pages/${id}`)).json()).page.objects[0]?.id;},lesson.pageId)).toBe('unfinished');await page.reload();await expect(page.getByRole('button',{name:'Restore unfinished work',exact:true})).toBeHidden();
});
