import {useEffect,useState} from 'react';
import {backupTargets,chooseBackupDirectory,removeBackupTarget,type BackupTarget} from '@/lib/recovery';
const providers=['Local folder','Google Drive','OneDrive','Dropbox','Nextcloud','Other'];
export function BackupConnections(){
  const [targets,setTargets]=useState<BackupTarget[]>([]),[provider,setProvider]=useState('Local folder'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{void backupTargets().then(setTargets).catch(()=>setError('Backup settings could not be read.'));},[]);
  async function connect(){setBusy(true);setError('');try{await chooseBackupDirectory(provider);setTargets(await backupTargets());}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Folder could not be connected.');}finally{setBusy(false);}}
  return <details className="rounded-xl border border-line p-4"><summary className="cursor-pointer text-sm font-semibold">Sync & backup folders</summary><p className="mt-3 text-xs leading-relaxed text-muted">Choose a folder already synced by your provider's desktop app. Kopy saves three rotating .kopy copies while teaching; the provider handles cloud uploads. This is file backup, not simultaneous editing across devices.</p><div className="mt-3 flex flex-wrap gap-2"><select aria-label="Backup provider" value={provider} onChange={e=>setProvider(e.target.value)} className="rounded-lg border border-line bg-base p-2 text-sm">{providers.map(p=><option key={p}>{p}</option>)}</select><button type="button" disabled={busy} onClick={()=>void connect()} className="rounded-lg bg-brand px-3 py-2 text-sm text-white">Choose synced folder</button></div>{targets.map(target=><div key={target.label} className="mt-3 flex items-center justify-between gap-3 text-xs"><span>{target.label} · {target.directory.name}</span><button type="button" className="underline" onClick={()=>void removeBackupTarget(target.label).then(()=>backupTargets()).then(setTargets)}>Disconnect</button></div>)}{error&&<p role="alert" className="mt-3 text-xs text-red-700">{error}</p>}<p className="mt-3 text-xs text-muted">Folder access requires supported desktop browsers. Use exported files and your device's provider picker on Android.</p></details>;
}
