import {Children,isValidElement,useEffect,useId,useLayoutEffect,useRef,useState,type ReactNode,type SelectHTMLAttributes} from 'react';
import {createPortal} from 'react-dom';
import {Icon} from './Icon';
import './custom-select.css';
type Option={value:string;label:ReactNode;disabled:boolean};
function optionsFrom(children:ReactNode):Option[]{return Children.toArray(children).flatMap(child=>{if(!isValidElement<{value?:string|number;children?:ReactNode;disabled?:boolean}>(child))return[];if(child.type==='option')return[{value:String(child.props.value??child.props.children??''),label:child.props.children,disabled:!!child.props.disabled}];return optionsFrom(child.props.children);});}
export function CustomSelect(props:SelectHTMLAttributes<HTMLSelectElement>){
 const {children,className,style,onChange,value,defaultValue,disabled,id,'aria-label':label,...rest}=props;
 const options=optionsFrom(children),[own,setOwn]=useState(String(defaultValue??options[0]?.value??'')),[open,setOpen]=useState(false),[active,setActive]=useState(0),[position,setPosition]=useState<{left:number;top:number;width:number;height:number}|null>(null);
 const selected=String(value??own),uid=useId(),native=useRef<HTMLSelectElement>(null),button=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null),[root,setRoot]=useState<HTMLElement>(document.body);
 const choose=(option:Option)=>{if(option.disabled||disabled)return;const select=native.current;if(select){select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));}setOpen(false);button.current?.focus({preventScroll:true});};
 useLayoutEffect(()=>{if(!open)return;setRoot(button.current?.closest<HTMLElement>('dialog,.kn-board')??document.body);const place=()=>{const r=button.current!.getBoundingClientRect(),width=Math.min(Math.max(180,r.width),innerWidth-16),wanted=Math.min(320,options.length*44+8),below=innerHeight-r.bottom-8,above=r.top-8,height=Math.max(44,Math.min(wanted,Math.max(below,above))),top=below>=Math.min(wanted,180)?r.bottom:Math.max(8,r.top-height);setPosition({left:Math.max(8,Math.min(r.left,innerWidth-width-8)),top,width,height});};place();window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);};},[open,options.length]);
 useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{if(!button.current?.contains(event.target as Node)&&!menu.current?.contains(event.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[open]);
 const start=()=>{if(disabled)return;setActive(Math.max(0,options.findIndex(o=>o.value===selected)));setOpen(current=>!current);};
 return <span className={`kn-select ${className??''}`} style={style}>
  <select {...rest} ref={native} value={value===undefined?own:value} disabled={disabled} tabIndex={-1} aria-hidden="true" hidden onChange={event=>{setOwn(event.target.value);onChange?.(event);}}>{children}</select>
  <button id={id} ref={button} type="button" role="combobox" aria-label={label} aria-expanded={open} aria-controls={open?uid:undefined} aria-haspopup="listbox" aria-activedescendant={open?`${uid}-${active}`:undefined} disabled={disabled} onClick={start} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();setOpen(false);return;}if(event.key==='Enter'||event.key===' '){event.preventDefault();if(open&&options[active])choose(options[active]);else start();return;}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();if(!open){setOpen(true);setActive(Math.max(0,options.findIndex(o=>o.value===selected)));return;}let next=event.key==='Home'?0:event.key==='End'?options.length-1:Math.max(0,Math.min(options.length-1,active+(event.key==='ArrowDown'?1:-1)));while(options[next]?.disabled&&next>0&&next<options.length-1)next+=event.key==='ArrowUp'?-1:1;setActive(next);document.getElementById(`${uid}-${next}`)?.scrollIntoView({block:'nearest'});}}}><span>{options.find(o=>o.value===selected)?.label??selected}</span><Icon name="chevronDown"/></button>
  {open&&position&&createPortal(<div ref={menu} id={uid} role="listbox" aria-label={label} data-toolbar-surface className="kn-select-menu kn-scroll" style={{position:'fixed',zIndex:11000,left:position.left,top:position.top,width:position.width,maxHeight:position.height}}>{options.map((option,index)=><button key={`${option.value}-${index}`} id={`${uid}-${index}`} type="button" role="option" aria-selected={selected===option.value} aria-disabled={option.disabled} data-select-value={option.value} className={active===index?'is-focused':''} disabled={option.disabled} onPointerDown={event=>event.preventDefault()} onClick={()=>choose(option)}><span>{option.label}</span>{selected===option.value&&<Icon name="check"/>}</button>)}</div>,root)}
 </span>;
}
