import {BoardPresets} from './BoardPresets';
import {useState} from 'react';
import type {AppProfile} from '@/db/schema';
import {BOARD_BACKGROUNDS,BOARD_PATTERNS} from '@/lib/constants';

/** Shared by first-run setup and Settings; all choices stay in the local profile. */
export function TeachingPreferences({value,onChange}:{value:Partial<AppProfile>;onChange:(patch:Partial<AppProfile>)=>void}) {
  const [measuredMm,setMeasuredMm]=useState('');
  const watermark=value.watermark??{enabled:false,text:'',position:'bottom-right' as const,opacity:.12};
  const ai=value.ai??{enabled:false,endpoint:'http://127.0.0.1:11434',model:'llama3.2'};
  return <div className="space-y-5">
    <fieldset className="rounded-xl border border-line p-4"><legend className="px-2 text-sm font-semibold">Your board</legend><BoardPresets value={value} onChange={onChange}/><div className="mt-4"/><div className="flex flex-wrap gap-2">{BOARD_BACKGROUNDS.map(b=><button type="button" key={b.value} aria-label={`Default background ${b.label}`} aria-pressed={value.boardBg===b.value} onClick={()=>onChange({boardBg:b.value})} className={`h-10 w-10 rounded-lg border-2 ${value.boardBg===b.value?'border-brand':'border-line'}`} style={{background:b.value}} title={b.label}/>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm">Pattern<select aria-label="Default board pattern" className="mt-1 w-full rounded-lg border border-line bg-base p-2" value={value.boardPattern??'none'} onChange={e=>onChange({boardPattern:e.target.value})}>{BOARD_PATTERNS.map(p=><option key={p.value} value={p.value}>{p.label}</option>)}</select></label><label className="text-sm">Default pen ink<input aria-label="Default pen color" type="color" value={value.defaultPenColor??'#10151b'} onChange={e=>onChange({defaultPenColor:e.target.value})} className="mt-1 block h-10 w-full rounded-lg border border-line bg-base p-1"/></label></div><p className="mt-3 text-xs text-muted">Defaults apply to new lessons. Existing pages keep their own background.</p></fieldset>
    <details className="rounded-xl border border-line p-4"><summary className="cursor-pointer text-sm font-semibold">Watermark, screen calibration & local AI</summary><div className="mt-4 space-y-6">
      <fieldset><legend className="mb-2 text-sm font-semibold">Teaching watermark</legend><label className="flex items-center gap-2 text-sm"><input aria-label="Enable teaching watermark" type="checkbox" checked={watermark.enabled} onChange={e=>onChange({watermark:{...watermark,enabled:e.target.checked}})}/>Show on the board</label><input aria-label="Watermark text" className="mt-2 w-full rounded-lg border border-line bg-base p-2" placeholder="Teacher or institution" maxLength={120} value={watermark.text} onChange={e=>onChange({watermark:{...watermark,text:e.target.value}})}/><div className="mt-2 grid grid-cols-2 gap-3"><label className="text-xs">Position<select aria-label="Watermark position" className="mt-1 w-full rounded-lg border border-line bg-base p-2" value={watermark.position} onChange={e=>onChange({watermark:{...watermark,position:e.target.value as typeof watermark.position}})}>{['center','top-left','top-right','bottom-left','bottom-right'].map(p=><option key={p} value={p}>{p.replaceAll('-',' ')}</option>)}</select></label><label className="text-xs">Opacity ({Math.round(watermark.opacity*100)}%)<input aria-label="Watermark opacity" type="range" min=".02" max=".5" step=".01" value={watermark.opacity} onChange={e=>onChange({watermark:{...watermark,opacity:Number(e.target.value)}})} className="mt-3 w-full"/></label></div></fieldset>
      <fieldset><legend className="mb-2 text-sm font-semibold">Physical ruler calibration</legend><p className="text-xs leading-relaxed text-muted">Measure this line on your display with a physical ruler. Calibration is specific to this display and browser zoom; repeat it after changing either.</p><div className="my-4 h-3 border-x-2 border-b-2 border-ink" style={{width:100}}/><div className="flex flex-wrap items-end gap-2"><label className="text-xs">Measured length (mm)<input aria-label="Calibration measured millimeters" type="number" min="2" max="1000" value={measuredMm} onChange={e=>setMeasuredMm(e.target.value)} className="mt-1 block w-32 rounded-lg border border-line bg-base p-2"/></label><button type="button" disabled={!(Number(measuredMm)>=2&&Number(measuredMm)<=1000)} onClick={()=>onChange({calibrationPxPerMm:100/Number(measuredMm)})} className="rounded-lg bg-brand px-3 py-2 text-sm text-white disabled:opacity-40">Calibrate</button><button type="button" onClick={()=>onChange({calibrationPxPerMm:96/25.4})} className="rounded-lg border border-line px-3 py-2 text-sm">Reset digital default</button></div><p className="mt-2 text-xs text-muted">{(value.calibrationPxPerMm??96/25.4).toFixed(2)} screen pixels per millimeter.</p></fieldset>
      <fieldset><legend className="mb-2 text-sm font-semibold">Optional local teaching assistant</legend><label className="flex items-center gap-2 text-sm"><input aria-label="Enable local AI" type="checkbox" checked={ai.enabled} onChange={e=>onChange({ai:{...ai,enabled:e.target.checked}})}/>Enable Ollama assistant</label><p className="mt-2 text-xs leading-relaxed text-muted">Requires your own running Ollama server and an installed model. No paid service or API key is built in. Only pressing Send contacts the server you choose; lesson files are not sent automatically.</p><label className="mt-3 block text-xs">Server URL<input aria-label="Local AI server URL" type="url" className="mt-1 w-full rounded-lg border border-line bg-base p-2" value={ai.endpoint} onChange={e=>onChange({ai:{...ai,endpoint:e.target.value}})}/></label><label className="mt-3 block text-xs">Installed model<input aria-label="Local AI model" maxLength={100} className="mt-1 w-full rounded-lg border border-line bg-base p-2" value={ai.model} onChange={e=>onChange({ai:{...ai,model:e.target.value}})}/></label><a href="https://docs.ollama.com/faq" target="_blank" rel="noopener noreferrer" className="mt-2 block text-xs text-brand-light underline">Ollama setup and browser origin instructions</a></fieldset>
    </div></details>
  </div>;
}
